[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bijax"
version = "0.1.1"
requires-python = ">=3.11"
dependencies = [
    "equinox>=0.12.1",
    "jax>=0.8.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=6.0.0",
    "optax>=0.2.4",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = "--cov=bijax --cov-report=term-missing"

[tool.pyright]
reportMissingSuperCall = false
extraPaths = ["src"]

[tool.ruff.lint]
ignore = ["F722", "E741", "E743"]
